[dependencies]
base = "0.13.2"
map = "9.0.1"
sha2 = "0.1.0"
base16 = "1.0.0"
sha3 = "0.1.1"

[dev-dependencies]
test = "2.0.0"
fuzz = "0.2.1"
bench = "1.0.0"

[toolchain]
moc = "0.13.0"
pocket-ic = "4.0.0"