#!/usr/bin/env elixir
# Regenerates src/MoonbeamZoneMap.mo from the Moonbeam→Base restore CSV.
#
# Usage:
#   elixir scripts/update_moonbeam_zone_map.exs
#   elixir scripts/update_moonbeam_zone_map.exs /path/to/export-zones-base-address-map.csv

default_csv =
  "/Users/dominicletz/projects/diode/moonbeam_death/export-zones-base-address-map.csv"

csv_path =
  case System.argv() do
    [path] -> path
    [] -> default_csv
    _ ->
      IO.puts(:stderr, "Usage: elixir scripts/update_moonbeam_zone_map.exs [csv_path]")
      System.halt(1)
  end

out_path = Path.expand("src/MoonbeamZoneMap.mo", Path.dirname(__DIR__))

unless File.exists?(csv_path) do
  IO.puts(:stderr, "CSV not found: #{csv_path}")
  System.halt(1)
end

normalize = fn addr ->
  addr
  |> String.trim()
  |> String.downcase()
end

valid_address? = fn addr ->
  String.match?(addr, ~r/^0x[0-9a-f]{40}$/)
end

{header, rows} =
  csv_path
  |> File.stream!()
  |> Stream.map(&String.trim/1)
  |> Stream.reject(&(&1 == ""))
  |> Enum.to_list()
  |> then(fn [h | rest] -> {String.split(h, ","), rest} end)

col = fn name ->
  case Enum.find_index(header, &(&1 == name)) do
    nil ->
      IO.puts(:stderr, "CSV missing column: #{name}")
      System.halt(1)

    idx ->
      idx
  end
end

kind_i = col.("Kind")
moon_i = col.("MoonbeamAddress")
base_i = col.("BaseAddress")

pairs =
  rows
  |> Enum.map(&String.split(&1, ","))
  |> Enum.filter(fn cols ->
    Enum.at(cols, kind_i) == "zone" and Enum.at(cols, base_i, "") != ""
  end)
  |> Enum.map(fn cols ->
    moon = normalize.(Enum.at(cols, moon_i))
    base = normalize.(Enum.at(cols, base_i))
    {moon, base}
  end)
  |> Enum.filter(fn {moon, base} ->
    valid_address?.(moon) and valid_address?.(base)
  end)
  |> Enum.uniq_by(fn {moon, _} -> moon end)
  |> Enum.sort_by(fn {moon, _} -> moon end)

if pairs == [] do
  IO.puts(:stderr, "No zone rows with BaseAddress found in #{csv_path}")
  System.halt(1)
end

version = Integer.to_string(System.system_time(:second))

pair_lines =
  pairs
  |> Enum.map(fn {moon, base} ->
    ~s|    ("#{moon}", "#{base}")|
  end)
  |> Enum.join(",\n")

content = """
import Text "mo:base/Text";

// Embedded Moonbeam → Base address map for one-shot upgrade migration.
// Keep in sync with ddrive Model.MoonbeamZoneMap (version #{version}).
// Generated by scripts/update_moonbeam_zone_map.exs from export-zones-base-address-map.csv.
// Keys/values are lowercase 0x-prefixed 20-byte addresses.
module MoonbeamZoneMap {
  public let version : Text = "#{version}";

  let pairs : [(Text, Text)] = [
#{pair_lines}
  ];

  public func normalize(addr : Text) : Text {
    Text.toLowercase(addr);
  };

  public func zone_base(moonbeam_zone_id : Text) : ?Text {
    let key = normalize(moonbeam_zone_id);
    for ((moon, base) in pairs.vals()) {
      if (moon == key) {
        return ?base;
      };
    };
    null;
  };
};
"""

File.write!(out_path, content)

IO.puts("Wrote #{length(pairs)} zone pairs to #{out_path}")
IO.puts("version=#{version}")
