name: mops test

on:
  push:
    branches:
      - letz/ci
      - ci
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install deps and run tests
        run: |
          . ./install_deps.sh
          mops format --check
          ./run_tests.sh
