name: mops test

on:
  push:
    branches:
      - letz/ci
      - ci
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dfinity/setup-dfx@main
      - uses: ZenVoich/setup-mops@v1

      - name: make sure moc is installed
        run: mops toolchain bin moc || mops toolchain use moc latest

      - name: install deps
        run: mops install

      - name: run tests
        run: ./run_tests.sh
